name: Tests
on:
  push:
    branches:
      - develop
      - main
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: asdf_install
        uses: asdf-vm/actions/install@v1
      - name: Install Python modules
        run: |
          pip install -r requirements.test.txt
      - name: Tests suite
        run: |
          python -m pytest tests
        env:
          API_TOKEN: ${{ secrets.OCTOPUS_ENERGY_API_TOKEN }}
